const SUPPORTED_LANGUAGES = [
  {
    "code": "zh-CN",
    "name": "简体中文",
    "dir": "ltr"
  },
  {
    "code": "zh-TW",
    "name": "繁體中文",
    "dir": "ltr"
  },
  {
    "code": "en",
    "name": "English",
    "dir": "ltr"
  },
  {
    "code": "es",
    "name": "Español",
    "dir": "ltr"
  },
  {
    "code": "fr",
    "name": "Français",
    "dir": "ltr"
  },
  {
    "code": "ar",
    "name": "العربية",
    "dir": "rtl"
  },
  {
    "code": "ru",
    "name": "Русский",
    "dir": "ltr"
  },
  {
    "code": "pt",
    "name": "Português",
    "dir": "ltr"
  },
  {
    "code": "de",
    "name": "Deutsch",
    "dir": "ltr"
  },
  {
    "code": "ja",
    "name": "日本語",
    "dir": "ltr"
  },
  {
    "code": "ko",
    "name": "한국어",
    "dir": "ltr"
  },
  {
    "code": "it",
    "name": "Italiano",
    "dir": "ltr"
  },
  {
    "code": "nl",
    "name": "Nederlands",
    "dir": "ltr"
  },
  {
    "code": "tr",
    "name": "Türkçe",
    "dir": "ltr"
  },
  {
    "code": "hi",
    "name": "हिन्दी",
    "dir": "ltr"
  },
  {
    "code": "bn",
    "name": "বাংলা",
    "dir": "ltr"
  },
  {
    "code": "ur",
    "name": "اردو",
    "dir": "rtl"
  },
  {
    "code": "id",
    "name": "Bahasa Indonesia",
    "dir": "ltr"
  },
  {
    "code": "vi",
    "name": "Tiếng Việt",
    "dir": "ltr"
  },
  {
    "code": "th",
    "name": "ไทย",
    "dir": "ltr"
  },
  {
    "code": "pl",
    "name": "Polski",
    "dir": "ltr"
  },
  {
    "code": "uk",
    "name": "Українська",
    "dir": "ltr"
  },
  {
    "code": "fa",
    "name": "فارسی",
    "dir": "rtl"
  },
  {
    "code": "he",
    "name": "עברית",
    "dir": "rtl"
  }
];
const LANGUAGE_PACKS = {
  "zh-CN": {
    "titleSuffix": "本地排班系统",
    "storageReady": "本地自动保存，打开后自动读取",
    "storageLoaded": "已读取本地保存数据",
    "tabs": [
      "排班台",
      "患者库",
      "医护库",
      "布局设置"
    ],
    "print": "打印",
    "export": "导出",
    "import": "导入",
    "reset": "全部重置",
    "clearCache": "清空所有缓存",
    "about": "关于作者和程序",
    "aboutTitle": "关于作者和程序",
    "aboutSubtitle": "开源 · 免费 · 祝福所有医护",
    "aboutClose": "关闭",
    "schedulePriority": "排班策略",
    "date": "日期",
    "weekMeta": "默认读取每周模板；周一至周六工作，周日休息；临时变化可保存为仅当前日期",
    "prevWeek": "上一周",
    "nextWeek": "下一周",
    "today": "今天",
    "staffBoard": "医护排班",
    "scheduleBoard": "今日排班",
    "autoSchedule": "生成长期周模板建议",
    "saveAsWeekly": "本周设为长期模板",
    "copyPrevious": "复制前一天",
    "clearDay": "清空当日",
    "language": "语言",
    "languageUpdated": "语言已切换"
  },
  "zh-TW": {
    "titleSuffix": "本地排班系統",
    "storageReady": "本地自動儲存，開啟後自動讀取",
    "storageLoaded": "已讀取本地儲存資料",
    "tabs": [
      "排班台",
      "病患庫",
      "醫護庫",
      "配置設定"
    ],
    "print": "列印",
    "export": "匯出",
    "import": "匯入",
    "reset": "全部重設",
    "clearCache": "清除所有快取",
    "about": "關於作者與程式",
    "aboutTitle": "關於作者與程式",
    "aboutSubtitle": "開源 · 免費 · 祝福所有醫護",
    "aboutClose": "關閉",
    "schedulePriority": "排班策略",
    "date": "日期",
    "weekMeta": "預設讀取每週範本；週一至週六工作，週日休息；臨時變更可只儲存目前日期",
    "prevWeek": "上一週",
    "nextWeek": "下一週",
    "today": "今天",
    "staffBoard": "醫護排班",
    "scheduleBoard": "今日排班",
    "autoSchedule": "產生長期週範本建議",
    "saveAsWeekly": "將本週設為長期範本",
    "copyPrevious": "複製前一天",
    "clearDay": "清除當日",
    "language": "語言",
    "languageUpdated": "語言已切換"
  },
  "en": {
    "titleSuffix": "Local Scheduler",
    "storageReady": "Auto-saved locally and loaded on next open",
    "storageLoaded": "Loaded local saved data",
    "tabs": [
      "Schedule",
      "Patients",
      "Staff",
      "Settings"
    ],
    "print": "Print",
    "export": "Export",
    "import": "Import",
    "reset": "Reset All",
    "clearCache": "Clear App Cache",
    "about": "About Author & App",
    "aboutTitle": "About the Author & App",
    "aboutSubtitle": "Open source · Free · Best wishes to all healthcare workers",
    "aboutClose": "Close",
    "schedulePriority": "Priority",
    "date": "Date",
    "weekMeta": "Uses weekly templates by default; Monday–Saturday working, Sunday rest; one-off changes can be saved for the selected date only",
    "prevWeek": "Previous Week",
    "nextWeek": "Next Week",
    "today": "Today",
    "staffBoard": "Staff Schedule",
    "scheduleBoard": "Daily Schedule",
    "autoSchedule": "Generate Recurring Weekly Template",
    "saveAsWeekly": "Set This Week as Recurring Template",
    "copyPrevious": "Copy Previous Day",
    "clearDay": "Clear Day",
    "language": "Language",
    "languageUpdated": "Language updated"
  },
  "es": {
    "titleSuffix": "Planificador local",
    "storageReady": "Guardado local automático y carga al abrir",
    "storageLoaded": "Datos locales cargados",
    "tabs": [
      "Horario",
      "Pacientes",
      "Personal",
      "Configuración"
    ],
    "print": "Imprimir",
    "export": "Exportar",
    "import": "Importar",
    "reset": "Restablecer todo",
    "clearCache": "Borrar caché",
    "about": "Acerca del autor y la aplicación",
    "aboutTitle": "Acerca del autor y la aplicación",
    "aboutSubtitle": "Código abierto · Gratis · Gracias al personal sanitario",
    "aboutClose": "Cerrar",
    "schedulePriority": "Prioridad",
    "date": "Fecha",
    "weekMeta": "Usa plantillas semanales; lunes a sábado laborables y domingo de descanso; los cambios puntuales se guardan solo para la fecha seleccionada",
    "prevWeek": "Semana anterior",
    "nextWeek": "Semana siguiente",
    "today": "Hoy",
    "staffBoard": "Horario del personal",
    "scheduleBoard": "Horario diario",
    "autoSchedule": "Generar plantilla semanal recurrente",
    "saveAsWeekly": "Guardar esta semana como plantilla",
    "copyPrevious": "Copiar día anterior",
    "clearDay": "Borrar día",
    "language": "Idioma",
    "languageUpdated": "Idioma actualizado"
  },
  "fr": {
    "titleSuffix": "Planificateur local",
    "storageReady": "Enregistrement local automatique et chargement à l’ouverture",
    "storageLoaded": "Données locales chargées",
    "tabs": [
      "Planning",
      "Patients",
      "Personnel",
      "Paramètres"
    ],
    "print": "Imprimer",
    "export": "Exporter",
    "import": "Importer",
    "reset": "Tout réinitialiser",
    "clearCache": "Vider le cache",
    "about": "À propos de l’auteur et du programme",
    "aboutTitle": "À propos de l’auteur et du programme",
    "aboutSubtitle": "Open source · Gratuit · Merci à tous les soignants",
    "aboutClose": "Fermer",
    "schedulePriority": "Priorité",
    "date": "Date",
    "weekMeta": "Modèles hebdomadaires par défaut ; travail du lundi au samedi, repos le dimanche ; les changements ponctuels ne concernent que la date sélectionnée",
    "prevWeek": "Semaine précédente",
    "nextWeek": "Semaine suivante",
    "today": "Aujourd’hui",
    "staffBoard": "Planning du personnel",
    "scheduleBoard": "Planning du jour",
    "autoSchedule": "Générer le modèle hebdomadaire récurrent",
    "saveAsWeekly": "Définir cette semaine comme modèle",
    "copyPrevious": "Copier le jour précédent",
    "clearDay": "Effacer le jour",
    "language": "Langue",
    "languageUpdated": "Langue mise à jour"
  },
  "ar": {
    "titleSuffix": "نظام جدولة محلي",
    "storageReady": "حفظ محلي تلقائي وتحميل عند الفتح",
    "storageLoaded": "تم تحميل البيانات المحلية",
    "tabs": [
      "الجدول",
      "المرضى",
      "الطاقم",
      "الإعدادات"
    ],
    "print": "طباعة",
    "export": "تصدير",
    "import": "استيراد",
    "reset": "إعادة ضبط الكل",
    "clearCache": "مسح الذاكرة المؤقتة",
    "about": "حول المؤلف والبرنامج",
    "aboutTitle": "حول المؤلف والبرنامج",
    "aboutSubtitle": "مفتوح المصدر · مجاني · شكرًا لجميع العاملين الصحيين",
    "aboutClose": "إغلاق",
    "schedulePriority": "الأولوية",
    "date": "التاريخ",
    "weekMeta": "تُستخدم القوالب الأسبوعية افتراضيًا؛ العمل من الاثنين إلى السبت والراحة يوم الأحد؛ تُحفظ التغييرات المؤقتة للتاريخ المحدد فقط",
    "prevWeek": "الأسبوع السابق",
    "nextWeek": "الأسبوع التالي",
    "today": "اليوم",
    "staffBoard": "جدول الطاقم",
    "scheduleBoard": "جدول اليوم",
    "autoSchedule": "إنشاء قالب أسبوعي متكرر",
    "saveAsWeekly": "تعيين هذا الأسبوع كقالب",
    "copyPrevious": "نسخ اليوم السابق",
    "clearDay": "مسح اليوم",
    "language": "اللغة",
    "languageUpdated": "تم تحديث اللغة"
  },
  "ru": {
    "titleSuffix": "Локальный планировщик",
    "storageReady": "Автосохранение локально и загрузка при открытии",
    "storageLoaded": "Локальные данные загружены",
    "tabs": [
      "Расписание",
      "Пациенты",
      "Персонал",
      "Настройки"
    ],
    "print": "Печать",
    "export": "Экспорт",
    "import": "Импорт",
    "reset": "Сбросить всё",
    "clearCache": "Очистить кэш",
    "about": "Об авторе и программе",
    "aboutTitle": "Об авторе и программе",
    "aboutSubtitle": "Открытый код · Бесплатно · Спасибо всем медикам",
    "aboutClose": "Закрыть",
    "schedulePriority": "Приоритет",
    "date": "Дата",
    "weekMeta": "По умолчанию используются недельные шаблоны; работа с понедельника по субботу, воскресенье — выходной; разовые изменения сохраняются только для выбранной даты",
    "prevWeek": "Предыдущая неделя",
    "nextWeek": "Следующая неделя",
    "today": "Сегодня",
    "staffBoard": "График персонала",
    "scheduleBoard": "Расписание на день",
    "autoSchedule": "Создать повторяющийся недельный шаблон",
    "saveAsWeekly": "Сохранить неделю как шаблон",
    "copyPrevious": "Копировать предыдущий день",
    "clearDay": "Очистить день",
    "language": "Язык",
    "languageUpdated": "Язык обновлён"
  },
  "pt": {
    "titleSuffix": "Agendador local",
    "storageReady": "Salvamento local automático e carregamento ao abrir",
    "storageLoaded": "Dados locais carregados",
    "tabs": [
      "Agenda",
      "Pacientes",
      "Equipe",
      "Configurações"
    ],
    "print": "Imprimir",
    "export": "Exportar",
    "import": "Importar",
    "reset": "Redefinir tudo",
    "clearCache": "Limpar cache",
    "about": "Sobre o autor e o programa",
    "aboutTitle": "Sobre o autor e o programa",
    "aboutSubtitle": "Código aberto · Gratuito · Obrigado a todos os profissionais de saúde",
    "aboutClose": "Fechar",
    "schedulePriority": "Prioridade",
    "date": "Data",
    "weekMeta": "Usa modelos semanais; trabalho de segunda a sábado e descanso no domingo; alterações pontuais valem apenas para a data selecionada",
    "prevWeek": "Semana anterior",
    "nextWeek": "Próxima semana",
    "today": "Hoje",
    "staffBoard": "Escala da equipe",
    "scheduleBoard": "Agenda diária",
    "autoSchedule": "Gerar modelo semanal recorrente",
    "saveAsWeekly": "Definir esta semana como modelo",
    "copyPrevious": "Copiar dia anterior",
    "clearDay": "Limpar dia",
    "language": "Idioma",
    "languageUpdated": "Idioma atualizado"
  },
  "de": {
    "titleSuffix": "Lokaler Dienstplaner",
    "storageReady": "Automatisch lokal gespeichert und beim Öffnen geladen",
    "storageLoaded": "Lokale Daten geladen",
    "tabs": [
      "Planung",
      "Patienten",
      "Personal",
      "Einstellungen"
    ],
    "print": "Drucken",
    "export": "Exportieren",
    "import": "Importieren",
    "reset": "Alles zurücksetzen",
    "clearCache": "Cache leeren",
    "about": "Über Autor und Programm",
    "aboutTitle": "Über Autor und Programm",
    "aboutSubtitle": "Open Source · Kostenlos · Danke an alle Gesundheitsfachkräfte",
    "aboutClose": "Schließen",
    "schedulePriority": "Priorität",
    "date": "Datum",
    "weekMeta": "Standardmäßig Wochenvorlagen; Montag bis Samstag Arbeit, Sonntag Ruhetag; einmalige Änderungen gelten nur für das gewählte Datum",
    "prevWeek": "Vorherige Woche",
    "nextWeek": "Nächste Woche",
    "today": "Heute",
    "staffBoard": "Personalplan",
    "scheduleBoard": "Tagesplan",
    "autoSchedule": "Wiederkehrende Wochenvorlage erstellen",
    "saveAsWeekly": "Diese Woche als Vorlage speichern",
    "copyPrevious": "Vortag kopieren",
    "clearDay": "Tag löschen",
    "language": "Sprache",
    "languageUpdated": "Sprache aktualisiert"
  },
  "ja": {
    "titleSuffix": "ローカル勤務表",
    "storageReady": "ローカルに自動保存し、次回起動時に読み込みます",
    "storageLoaded": "ローカル保存データを読み込みました",
    "tabs": [
      "勤務表",
      "患者",
      "医療スタッフ",
      "設定"
    ],
    "print": "印刷",
    "export": "エクスポート",
    "import": "インポート",
    "reset": "すべてリセット",
    "clearCache": "キャッシュを消去",
    "about": "作者とプログラムについて",
    "aboutTitle": "作者とプログラムについて",
    "aboutSubtitle": "オープンソース · 完全無料 · すべての医療従事者に感謝",
    "aboutClose": "閉じる",
    "schedulePriority": "優先方式",
    "date": "日付",
    "weekMeta": "週次テンプレートを使用。月曜〜土曜は稼働、日曜は休み。臨時変更は選択日のみに保存できます",
    "prevWeek": "前の週",
    "nextWeek": "次の週",
    "today": "今日",
    "staffBoard": "スタッフ勤務表",
    "scheduleBoard": "当日の勤務表",
    "autoSchedule": "長期週次テンプレートを生成",
    "saveAsWeekly": "今週を長期テンプレートに設定",
    "copyPrevious": "前日をコピー",
    "clearDay": "当日をクリア",
    "language": "言語",
    "languageUpdated": "言語を更新しました"
  },
  "ko": {
    "titleSuffix": "로컬 일정 시스템",
    "storageReady": "로컬 자동 저장 및 실행 시 불러오기",
    "storageLoaded": "로컬 저장 데이터를 불러왔습니다",
    "tabs": [
      "일정",
      "환자",
      "의료진",
      "설정"
    ],
    "print": "인쇄",
    "export": "내보내기",
    "import": "가져오기",
    "reset": "전체 초기화",
    "clearCache": "캐시 지우기",
    "about": "작성자와 프로그램 정보",
    "aboutTitle": "작성자와 프로그램 정보",
    "aboutSubtitle": "오픈 소스 · 무료 · 모든 의료진께 감사드립니다",
    "aboutClose": "닫기",
    "schedulePriority": "우선순위",
    "date": "날짜",
    "weekMeta": "주간 템플릿을 기본 사용하며 월~토 운영, 일요일 휴무입니다. 임시 변경은 선택한 날짜에만 저장됩니다",
    "prevWeek": "이전 주",
    "nextWeek": "다음 주",
    "today": "오늘",
    "staffBoard": "의료진 일정",
    "scheduleBoard": "일일 일정",
    "autoSchedule": "반복 주간 템플릿 생성",
    "saveAsWeekly": "이번 주를 템플릿으로 설정",
    "copyPrevious": "전날 복사",
    "clearDay": "당일 지우기",
    "language": "언어",
    "languageUpdated": "언어가 변경되었습니다"
  },
  "it": {
    "titleSuffix": "Pianificatore locale",
    "storageReady": "Salvataggio locale automatico e caricamento all’apertura",
    "storageLoaded": "Dati locali caricati",
    "tabs": [
      "Pianificazione",
      "Pazienti",
      "Personale",
      "Impostazioni"
    ],
    "print": "Stampa",
    "export": "Esporta",
    "import": "Importa",
    "reset": "Reimposta tutto",
    "clearCache": "Svuota cache",
    "about": "Informazioni su autore e programma",
    "aboutTitle": "Informazioni su autore e programma",
    "aboutSubtitle": "Open source · Gratuito · Grazie a tutto il personale sanitario",
    "aboutClose": "Chiudi",
    "schedulePriority": "Priorità",
    "date": "Data",
    "weekMeta": "Usa modelli settimanali; lavoro da lunedì a sabato, domenica riposo; le modifiche occasionali valgono solo per la data selezionata",
    "prevWeek": "Settimana precedente",
    "nextWeek": "Settimana successiva",
    "today": "Oggi",
    "staffBoard": "Turni del personale",
    "scheduleBoard": "Programma giornaliero",
    "autoSchedule": "Genera modello settimanale ricorrente",
    "saveAsWeekly": "Imposta questa settimana come modello",
    "copyPrevious": "Copia giorno precedente",
    "clearDay": "Cancella giorno",
    "language": "Lingua",
    "languageUpdated": "Lingua aggiornata"
  },
  "nl": {
    "titleSuffix": "Lokale planner",
    "storageReady": "Automatisch lokaal opgeslagen en geladen bij openen",
    "storageLoaded": "Lokale gegevens geladen",
    "tabs": [
      "Planning",
      "Patiënten",
      "Personeel",
      "Instellingen"
    ],
    "print": "Afdrukken",
    "export": "Exporteren",
    "import": "Importeren",
    "reset": "Alles resetten",
    "clearCache": "Cache wissen",
    "about": "Over auteur en programma",
    "aboutTitle": "Over auteur en programma",
    "aboutSubtitle": "Open source · Gratis · Dank aan alle zorgverleners",
    "aboutClose": "Sluiten",
    "schedulePriority": "Prioriteit",
    "date": "Datum",
    "weekMeta": "Gebruikt standaard weeksjablonen; maandag t/m zaterdag geopend, zondag rustdag; eenmalige wijzigingen gelden alleen voor de gekozen datum",
    "prevWeek": "Vorige week",
    "nextWeek": "Volgende week",
    "today": "Vandaag",
    "staffBoard": "Personeelsplanning",
    "scheduleBoard": "Dagplanning",
    "autoSchedule": "Terugkerend weeksjabloon maken",
    "saveAsWeekly": "Deze week als sjabloon instellen",
    "copyPrevious": "Vorige dag kopiëren",
    "clearDay": "Dag wissen",
    "language": "Taal",
    "languageUpdated": "Taal bijgewerkt"
  },
  "tr": {
    "titleSuffix": "Yerel çizelge sistemi",
    "storageReady": "Yerel otomatik kayıt ve açılışta yükleme",
    "storageLoaded": "Yerel veriler yüklendi",
    "tabs": [
      "Çizelge",
      "Hastalar",
      "Personel",
      "Ayarlar"
    ],
    "print": "Yazdır",
    "export": "Dışa aktar",
    "import": "İçe aktar",
    "reset": "Tümünü sıfırla",
    "clearCache": "Önbelleği temizle",
    "about": "Yazar ve program hakkında",
    "aboutTitle": "Yazar ve program hakkında",
    "aboutSubtitle": "Açık kaynak · Ücretsiz · Tüm sağlık çalışanlarına teşekkürler",
    "aboutClose": "Kapat",
    "schedulePriority": "Öncelik",
    "date": "Tarih",
    "weekMeta": "Haftalık şablonlar kullanılır; pazartesi-cumartesi çalışma, pazar dinlenme; tek seferlik değişiklikler yalnızca seçilen tarihe kaydedilir",
    "prevWeek": "Önceki hafta",
    "nextWeek": "Sonraki hafta",
    "today": "Bugün",
    "staffBoard": "Personel çizelgesi",
    "scheduleBoard": "Günlük çizelge",
    "autoSchedule": "Yinelenen haftalık şablon oluştur",
    "saveAsWeekly": "Bu haftayı şablon yap",
    "copyPrevious": "Önceki günü kopyala",
    "clearDay": "Günü temizle",
    "language": "Dil",
    "languageUpdated": "Dil güncellendi"
  },
  "hi": {
    "titleSuffix": "Local Scheduler",
    "storageReady": "Auto-saved locally and loaded on next open",
    "storageLoaded": "Loaded local saved data",
    "tabs": [
      "Schedule",
      "Patients",
      "Staff",
      "Settings"
    ],
    "print": "Print",
    "export": "Export",
    "import": "Import",
    "reset": "Reset All",
    "clearCache": "Clear App Cache",
    "about": "About Author & App",
    "aboutTitle": "About the Author & App",
    "aboutSubtitle": "Open source · Free · Best wishes to all healthcare workers",
    "aboutClose": "Close",
    "schedulePriority": "Priority",
    "date": "Date",
    "weekMeta": "Uses weekly templates by default; Monday–Saturday working, Sunday rest; one-off changes can be saved for the selected date only",
    "prevWeek": "Previous Week",
    "nextWeek": "Next Week",
    "today": "Today",
    "staffBoard": "Staff Schedule",
    "scheduleBoard": "Daily Schedule",
    "autoSchedule": "Generate Recurring Weekly Template",
    "saveAsWeekly": "Set This Week as Recurring Template",
    "copyPrevious": "Copy Previous Day",
    "clearDay": "Clear Day",
    "language": "Language",
    "languageUpdated": "Language updated"
  },
  "bn": {
    "titleSuffix": "Local Scheduler",
    "storageReady": "Auto-saved locally and loaded on next open",
    "storageLoaded": "Loaded local saved data",
    "tabs": [
      "Schedule",
      "Patients",
      "Staff",
      "Settings"
    ],
    "print": "Print",
    "export": "Export",
    "import": "Import",
    "reset": "Reset All",
    "clearCache": "Clear App Cache",
    "about": "About Author & App",
    "aboutTitle": "About the Author & App",
    "aboutSubtitle": "Open source · Free · Best wishes to all healthcare workers",
    "aboutClose": "Close",
    "schedulePriority": "Priority",
    "date": "Date",
    "weekMeta": "Uses weekly templates by default; Monday–Saturday working, Sunday rest; one-off changes can be saved for the selected date only",
    "prevWeek": "Previous Week",
    "nextWeek": "Next Week",
    "today": "Today",
    "staffBoard": "Staff Schedule",
    "scheduleBoard": "Daily Schedule",
    "autoSchedule": "Generate Recurring Weekly Template",
    "saveAsWeekly": "Set This Week as Recurring Template",
    "copyPrevious": "Copy Previous Day",
    "clearDay": "Clear Day",
    "language": "Language",
    "languageUpdated": "Language updated"
  },
  "ur": {
    "titleSuffix": "Local Scheduler",
    "storageReady": "Auto-saved locally and loaded on next open",
    "storageLoaded": "Loaded local saved data",
    "tabs": [
      "Schedule",
      "Patients",
      "Staff",
      "Settings"
    ],
    "print": "Print",
    "export": "Export",
    "import": "Import",
    "reset": "Reset All",
    "clearCache": "Clear App Cache",
    "about": "About Author & App",
    "aboutTitle": "About the Author & App",
    "aboutSubtitle": "Open source · Free · Best wishes to all healthcare workers",
    "aboutClose": "Close",
    "schedulePriority": "Priority",
    "date": "Date",
    "weekMeta": "Uses weekly templates by default; Monday–Saturday working, Sunday rest; one-off changes can be saved for the selected date only",
    "prevWeek": "Previous Week",
    "nextWeek": "Next Week",
    "today": "Today",
    "staffBoard": "Staff Schedule",
    "scheduleBoard": "Daily Schedule",
    "autoSchedule": "Generate Recurring Weekly Template",
    "saveAsWeekly": "Set This Week as Recurring Template",
    "copyPrevious": "Copy Previous Day",
    "clearDay": "Clear Day",
    "language": "Language",
    "languageUpdated": "Language updated"
  },
  "id": {
    "titleSuffix": "Local Scheduler",
    "storageReady": "Auto-saved locally and loaded on next open",
    "storageLoaded": "Loaded local saved data",
    "tabs": [
      "Schedule",
      "Patients",
      "Staff",
      "Settings"
    ],
    "print": "Print",
    "export": "Export",
    "import": "Import",
    "reset": "Reset All",
    "clearCache": "Clear App Cache",
    "about": "About Author & App",
    "aboutTitle": "About the Author & App",
    "aboutSubtitle": "Open source · Free · Best wishes to all healthcare workers",
    "aboutClose": "Close",
    "schedulePriority": "Priority",
    "date": "Date",
    "weekMeta": "Uses weekly templates by default; Monday–Saturday working, Sunday rest; one-off changes can be saved for the selected date only",
    "prevWeek": "Previous Week",
    "nextWeek": "Next Week",
    "today": "Today",
    "staffBoard": "Staff Schedule",
    "scheduleBoard": "Daily Schedule",
    "autoSchedule": "Generate Recurring Weekly Template",
    "saveAsWeekly": "Set This Week as Recurring Template",
    "copyPrevious": "Copy Previous Day",
    "clearDay": "Clear Day",
    "language": "Language",
    "languageUpdated": "Language updated"
  },
  "vi": {
    "titleSuffix": "Local Scheduler",
    "storageReady": "Auto-saved locally and loaded on next open",
    "storageLoaded": "Loaded local saved data",
    "tabs": [
      "Schedule",
      "Patients",
      "Staff",
      "Settings"
    ],
    "print": "Print",
    "export": "Export",
    "import": "Import",
    "reset": "Reset All",
    "clearCache": "Clear App Cache",
    "about": "About Author & App",
    "aboutTitle": "About the Author & App",
    "aboutSubtitle": "Open source · Free · Best wishes to all healthcare workers",
    "aboutClose": "Close",
    "schedulePriority": "Priority",
    "date": "Date",
    "weekMeta": "Uses weekly templates by default; Monday–Saturday working, Sunday rest; one-off changes can be saved for the selected date only",
    "prevWeek": "Previous Week",
    "nextWeek": "Next Week",
    "today": "Today",
    "staffBoard": "Staff Schedule",
    "scheduleBoard": "Daily Schedule",
    "autoSchedule": "Generate Recurring Weekly Template",
    "saveAsWeekly": "Set This Week as Recurring Template",
    "copyPrevious": "Copy Previous Day",
    "clearDay": "Clear Day",
    "language": "Language",
    "languageUpdated": "Language updated"
  },
  "th": {
    "titleSuffix": "Local Scheduler",
    "storageReady": "Auto-saved locally and loaded on next open",
    "storageLoaded": "Loaded local saved data",
    "tabs": [
      "Schedule",
      "Patients",
      "Staff",
      "Settings"
    ],
    "print": "Print",
    "export": "Export",
    "import": "Import",
    "reset": "Reset All",
    "clearCache": "Clear App Cache",
    "about": "About Author & App",
    "aboutTitle": "About the Author & App",
    "aboutSubtitle": "Open source · Free · Best wishes to all healthcare workers",
    "aboutClose": "Close",
    "schedulePriority": "Priority",
    "date": "Date",
    "weekMeta": "Uses weekly templates by default; Monday–Saturday working, Sunday rest; one-off changes can be saved for the selected date only",
    "prevWeek": "Previous Week",
    "nextWeek": "Next Week",
    "today": "Today",
    "staffBoard": "Staff Schedule",
    "scheduleBoard": "Daily Schedule",
    "autoSchedule": "Generate Recurring Weekly Template",
    "saveAsWeekly": "Set This Week as Recurring Template",
    "copyPrevious": "Copy Previous Day",
    "clearDay": "Clear Day",
    "language": "Language",
    "languageUpdated": "Language updated"
  },
  "pl": {
    "titleSuffix": "Local Scheduler",
    "storageReady": "Auto-saved locally and loaded on next open",
    "storageLoaded": "Loaded local saved data",
    "tabs": [
      "Schedule",
      "Patients",
      "Staff",
      "Settings"
    ],
    "print": "Print",
    "export": "Export",
    "import": "Import",
    "reset": "Reset All",
    "clearCache": "Clear App Cache",
    "about": "About Author & App",
    "aboutTitle": "About the Author & App",
    "aboutSubtitle": "Open source · Free · Best wishes to all healthcare workers",
    "aboutClose": "Close",
    "schedulePriority": "Priority",
    "date": "Date",
    "weekMeta": "Uses weekly templates by default; Monday–Saturday working, Sunday rest; one-off changes can be saved for the selected date only",
    "prevWeek": "Previous Week",
    "nextWeek": "Next Week",
    "today": "Today",
    "staffBoard": "Staff Schedule",
    "scheduleBoard": "Daily Schedule",
    "autoSchedule": "Generate Recurring Weekly Template",
    "saveAsWeekly": "Set This Week as Recurring Template",
    "copyPrevious": "Copy Previous Day",
    "clearDay": "Clear Day",
    "language": "Language",
    "languageUpdated": "Language updated"
  },
  "uk": {
    "titleSuffix": "Local Scheduler",
    "storageReady": "Auto-saved locally and loaded on next open",
    "storageLoaded": "Loaded local saved data",
    "tabs": [
      "Schedule",
      "Patients",
      "Staff",
      "Settings"
    ],
    "print": "Print",
    "export": "Export",
    "import": "Import",
    "reset": "Reset All",
    "clearCache": "Clear App Cache",
    "about": "About Author & App",
    "aboutTitle": "About the Author & App",
    "aboutSubtitle": "Open source · Free · Best wishes to all healthcare workers",
    "aboutClose": "Close",
    "schedulePriority": "Priority",
    "date": "Date",
    "weekMeta": "Uses weekly templates by default; Monday–Saturday working, Sunday rest; one-off changes can be saved for the selected date only",
    "prevWeek": "Previous Week",
    "nextWeek": "Next Week",
    "today": "Today",
    "staffBoard": "Staff Schedule",
    "scheduleBoard": "Daily Schedule",
    "autoSchedule": "Generate Recurring Weekly Template",
    "saveAsWeekly": "Set This Week as Recurring Template",
    "copyPrevious": "Copy Previous Day",
    "clearDay": "Clear Day",
    "language": "Language",
    "languageUpdated": "Language updated"
  },
  "fa": {
    "titleSuffix": "Local Scheduler",
    "storageReady": "Auto-saved locally and loaded on next open",
    "storageLoaded": "Loaded local saved data",
    "tabs": [
      "Schedule",
      "Patients",
      "Staff",
      "Settings"
    ],
    "print": "Print",
    "export": "Export",
    "import": "Import",
    "reset": "Reset All",
    "clearCache": "Clear App Cache",
    "about": "About Author & App",
    "aboutTitle": "About the Author & App",
    "aboutSubtitle": "Open source · Free · Best wishes to all healthcare workers",
    "aboutClose": "Close",
    "schedulePriority": "Priority",
    "date": "Date",
    "weekMeta": "Uses weekly templates by default; Monday–Saturday working, Sunday rest; one-off changes can be saved for the selected date only",
    "prevWeek": "Previous Week",
    "nextWeek": "Next Week",
    "today": "Today",
    "staffBoard": "Staff Schedule",
    "scheduleBoard": "Daily Schedule",
    "autoSchedule": "Generate Recurring Weekly Template",
    "saveAsWeekly": "Set This Week as Recurring Template",
    "copyPrevious": "Copy Previous Day",
    "clearDay": "Clear Day",
    "language": "Language",
    "languageUpdated": "Language updated"
  },
  "he": {
    "titleSuffix": "Local Scheduler",
    "storageReady": "Auto-saved locally and loaded on next open",
    "storageLoaded": "Loaded local saved data",
    "tabs": [
      "Schedule",
      "Patients",
      "Staff",
      "Settings"
    ],
    "print": "Print",
    "export": "Export",
    "import": "Import",
    "reset": "Reset All",
    "clearCache": "Clear App Cache",
    "about": "About Author & App",
    "aboutTitle": "About the Author & App",
    "aboutSubtitle": "Open source · Free · Best wishes to all healthcare workers",
    "aboutClose": "Close",
    "schedulePriority": "Priority",
    "date": "Date",
    "weekMeta": "Uses weekly templates by default; Monday–Saturday working, Sunday rest; one-off changes can be saved for the selected date only",
    "prevWeek": "Previous Week",
    "nextWeek": "Next Week",
    "today": "Today",
    "staffBoard": "Staff Schedule",
    "scheduleBoard": "Daily Schedule",
    "autoSchedule": "Generate Recurring Weekly Template",
    "saveAsWeekly": "Set This Week as Recurring Template",
    "copyPrevious": "Copy Previous Day",
    "clearDay": "Clear Day",
    "language": "Language",
    "languageUpdated": "Language updated"
  }
};

Object.keys(LANGUAGE_PACKS).forEach((code) => {
  const pack = LANGUAGE_PACKS[code];
  if (!pack.aboutAuthorText) {
    pack.aboutAuthorText = code === "zh-CN"
      ? "作者本人是透析患者，程序完全开源，完全免费。"
      : code === "zh-TW"
        ? "作者本人是透析患者，程式完全開源，完全免費。"
        : "The author is a dialysis patient. This program is fully open source and completely free.";
  }
  if (!pack.aboutThanksText) {
    pack.aboutThanksText = code === "zh-CN"
      ? "感谢世界上所有的医护，希望你们每天都开开心心，健健康康。"
      : code === "zh-TW"
        ? "感謝世界上所有的醫護，希望你們每天都開開心心，健健康康。"
        : "Thank you to all healthcare workers around the world. May you be happy and healthy every day.";
  }
  if (!pack.aboutContactPrefix) {
    pack.aboutContactPrefix = code === "zh-CN"
      ? "有任何需求、建议或问题，欢迎联系："
      : code === "zh-TW"
        ? "如有任何需求、建議或問題，歡迎聯絡："
        : "For requests, suggestions, or questions, contact:";
  }
});

window.SUPPORTED_LANGUAGES=SUPPORTED_LANGUAGES;window.LANGUAGE_PACKS=LANGUAGE_PACKS;

const DYNAMIC_MESSAGES = {
  "zh-CN": {
    "machinePausedCannotAssign": "{machineId} 号机当前已暂停，不能新增或保留患者安排。请先恢复机器，或将患者安排到其他机器。",
    "patientMachineMismatch": "{patientName} 需要{treatment}，且分区必须匹配患者组别或传染标识；不能安排到 {machineId}（{machineType}，{machineZone}）。",
    "fixedMachineWeeklyConflict": "{patientName} 已长期固定在 {fixedMachineId} 号机。每周模板不能改到 {machineId} 号机；如只是临时换位，请把保存范围改为“仅当前日期”。",
    "fixedMachinePaused": "固定机位 {machineId} 当前已暂停，不能新设为长期固定机位。请先恢复机器，或选择其他机器。",
    "fixedMachineMissing": "固定机位 {machineId} 当前不存在，请重新选择。",
    "fixedMachineIncompatible": "{patientName} 不能固定在 {machineId}（{machineType}，{machineZone}）。请检查治疗类型、护理组别和感染标识。",
    "defaultLayoutRestoredDataKept": "已恢复默认 60 台布局，患者、医护和排班数据已保留",
    "sundayNoWeeklyStaffTemplate": "周日休息，不保存为每周医护模板；可切换为仅当前日期",
    "sundayNoWeeklyPatientTemplate": "周日休息，不保存为每周患者模板；可切换为仅当前日期",
    "scheduleSaved": "排班已保存",
    "weeklyTemplateRemoved": "每周模板已移除",
    "dayScheduleRemoved": "当日排班已移除",
    "enterPatientName": "请填写患者姓名",
    "patientSaved": "患者资料已保存",
    "patientDeleted": "患者已删除",
    "selectMachineForPatient": "请在机器格子中选择 {patientName}",
    "assignPatientInMachineGrid": "请在机器格子中安排患者",
    "enterStaffName": "请填写医护姓名",
    "staffSaved": "医护资料已保存",
    "staffDeleted": "医护已删除",
    "staffAvailableInSchedule": "{staffName} 可在医护排班表中选择",
    "enterDemoCount": "请至少输入一种演示数据数量",
    "infectiousDemoCountExceeded": "四类传染患者合计 {infectiousCount} 名，不能超过患者总数 {patientCount} 名",
    "noDemoData": "没有演示数据可清除",
    "demoDataCleared": "演示数据已清除",
    "layoutApplied": "机器布局已应用",
    "default60LayoutRestored": "已恢复默认 60 台机器布局",
    "applyLayoutFirst": "先应用布局，再设置机器属性",
    "emptySlotCannotPause": "空位不能暂停",
    "emptySlotOnlyRestore": "空位只能恢复，不能设置类型或特殊区",
    "selectMachineType": "请选择要设置的机器类型",
    "nothingToSaveThisWeek": "本周没有可保存的患者或医护排班",
    "weekSavedAsRecurringTemplate": "本周已保存为以后长期循环的周模板",
    "noPreviousDaySchedule": "前一天没有排班",
    "previousDayCopied": "已复制前一天排班",
    "noScheduleToday": "当日没有排班",
    "dayScheduleCleared": "当日排班已清空",
    "dataImported": "数据已导入",
    "importFileUnrecognized": "导入文件无法识别",
    "allReset": "已全部重置",
    "machineNotInLayout": "机器编号不在当前布局中",
    "slotNotInLayout": "机位不在当前布局中",
    "keepAtLeastOneMachine": "至少保留 1 台机器",
    "duplicateDialysisNoConfirm": "透析号与 {patientName} 重复，仍要保存吗？",
    "deletePatientConfirm": "确定删除 {patientName} 的资料和相关排班吗？",
    "duplicateStaffNoConfirm": "工号与 {staffName} 重复，仍要保存吗？",
    "deleteStaffConfirm": "确定删除 {staffName} 的资料和相关医护排班吗？",
    "clearDemoConfirm": "确定清除 {patientCount} 名演示患者和 {staffCount} 名演示医护吗？",
    "layoutHidesAssignmentsConfirm": "新布局会隐藏 {count} 条已排记录，仍要应用吗？",
    "copyOverwritesCurrentDateConfirm": "当前日期已有排班，复制会覆盖，继续吗？",
    "clearDateScheduleConfirm": "确定清空 {date} 的排班吗？"
  },
  "zh-TW": {
    "machinePausedCannotAssign": "{machineId} 號機目前已暫停，不能新增或保留病患安排。請先恢復機器，或將病患安排到其他機器。",
    "patientMachineMismatch": "{patientName} 需要{treatment}，且分區必須符合病患組別或傳染標識；不能安排到 {machineId}（{machineType}，{machineZone}）。",
    "fixedMachineWeeklyConflict": "{patientName} 已長期固定在 {fixedMachineId} 號機。每週範本不能改到 {machineId} 號機；如只是臨時換位，請把儲存範圍改為「僅目前日期」。",
    "fixedMachinePaused": "固定機位 {machineId} 目前已暫停，不能新設為長期固定機位。請先恢復機器，或選擇其他機器。",
    "fixedMachineMissing": "固定機位 {machineId} 目前不存在，請重新選擇。",
    "fixedMachineIncompatible": "{patientName} 不能固定在 {machineId}（{machineType}，{machineZone}）。請檢查治療類型、護理組別及感染標識。",
    "defaultLayoutRestoredDataKept": "已恢復預設60台配置，病患、醫護及排班資料已保留",
    "sundayNoWeeklyStaffTemplate": "週日休息，不儲存為每週醫護範本；可切換為僅目前日期",
    "sundayNoWeeklyPatientTemplate": "週日休息，不儲存為每週病患範本；可切換為僅目前日期",
    "scheduleSaved": "排班已儲存",
    "weeklyTemplateRemoved": "每週範本已移除",
    "dayScheduleRemoved": "當日排班已移除",
    "enterPatientName": "請填寫病患姓名",
    "patientSaved": "病患資料已儲存",
    "patientDeleted": "病患已刪除",
    "selectMachineForPatient": "請在機器格中選擇 {patientName}",
    "assignPatientInMachineGrid": "請在機器格中安排病患",
    "enterStaffName": "請填寫醫護姓名",
    "staffSaved": "醫護資料已儲存",
    "staffDeleted": "醫護已刪除",
    "staffAvailableInSchedule": "{staffName} 可在醫護排班表中選擇",
    "enterDemoCount": "請至少輸入一種示範資料數量",
    "infectiousDemoCountExceeded": "四類傳染病患合計 {infectiousCount} 名，不能超過病患總數 {patientCount} 名",
    "noDemoData": "沒有示範資料可清除",
    "demoDataCleared": "示範資料已清除",
    "layoutApplied": "機器配置已套用",
    "default60LayoutRestored": "已恢復預設60台機器配置",
    "applyLayoutFirst": "請先套用配置，再設定機器屬性",
    "emptySlotCannotPause": "空位不能暫停",
    "emptySlotOnlyRestore": "空位只能恢復，不能設定類型或特殊區",
    "selectMachineType": "請選擇要設定的機器類型",
    "nothingToSaveThisWeek": "本週沒有可儲存的病患或醫護排班",
    "weekSavedAsRecurringTemplate": "本週已儲存為日後長期循環的週範本",
    "noPreviousDaySchedule": "前一天沒有排班",
    "previousDayCopied": "已複製前一天排班",
    "noScheduleToday": "當日沒有排班",
    "dayScheduleCleared": "當日排班已清除",
    "dataImported": "資料已匯入",
    "importFileUnrecognized": "無法辨識匯入檔案",
    "allReset": "已全部重設",
    "machineNotInLayout": "機器編號不在目前配置中",
    "slotNotInLayout": "機位不在目前配置中",
    "keepAtLeastOneMachine": "至少保留1台機器",
    "duplicateDialysisNoConfirm": "透析號與 {patientName} 重複，仍要儲存嗎？",
    "deletePatientConfirm": "確定刪除 {patientName} 的資料及相關排班嗎？",
    "duplicateStaffNoConfirm": "工號與 {staffName} 重複，仍要儲存嗎？",
    "deleteStaffConfirm": "確定刪除 {staffName} 的資料及相關醫護排班嗎？",
    "clearDemoConfirm": "確定清除 {patientCount} 名示範病患及 {staffCount} 名示範醫護嗎？",
    "layoutHidesAssignmentsConfirm": "新配置會隱藏 {count} 筆已排紀錄，仍要套用嗎？",
    "copyOverwritesCurrentDateConfirm": "目前日期已有排班，複製會覆蓋，是否繼續？",
    "clearDateScheduleConfirm": "確定清除 {date} 的排班嗎？"
  },
  "en": {
    "machinePausedCannotAssign": "Machine {machineId} is paused. Patient assignments cannot be added or retained. Restore the machine or use another compatible machine.",
    "patientMachineMismatch": "{patientName} requires {treatment}. The zone must match the patient group or infection status. Machine {machineId} ({machineType}, {machineZone}) is not compatible.",
    "fixedMachineWeeklyConflict": "{patientName} is permanently assigned to machine {fixedMachineId}. A weekly template cannot move the patient to machine {machineId}. For a temporary move, save it for the selected date only.",
    "fixedMachinePaused": "Fixed machine {machineId} is paused and cannot be newly assigned as a permanent machine. Restore it or choose another machine.",
    "fixedMachineMissing": "Fixed machine {machineId} does not exist. Choose another machine.",
    "fixedMachineIncompatible": "{patientName} cannot be fixed to machine {machineId} ({machineType}, {machineZone}). Check treatment type, care group, and infection status.",
    "defaultLayoutRestoredDataKept": "The default 60-machine layout was restored. Patient, staff, and schedule data were retained.",
    "sundayNoWeeklyStaffTemplate": "Sunday is a rest day and cannot be saved as a recurring staff template. Save it for the selected date only.",
    "sundayNoWeeklyPatientTemplate": "Sunday is a rest day and cannot be saved as a recurring patient template. Save it for the selected date only.",
    "scheduleSaved": "Schedule saved",
    "weeklyTemplateRemoved": "Weekly template removed",
    "dayScheduleRemoved": "Daily schedule removed",
    "enterPatientName": "Enter the patient name",
    "patientSaved": "Patient record saved",
    "patientDeleted": "Patient deleted",
    "selectMachineForPatient": "Select a machine for {patientName}",
    "assignPatientInMachineGrid": "Assign a patient in the machine grid",
    "enterStaffName": "Enter the staff name",
    "staffSaved": "Staff record saved",
    "staffDeleted": "Staff member deleted",
    "staffAvailableInSchedule": "{staffName} can now be selected in the staff schedule",
    "enterDemoCount": "Enter at least one demo-data quantity",
    "infectiousDemoCountExceeded": "The combined infectious-patient count ({infectiousCount}) cannot exceed the total patient count ({patientCount}).",
    "noDemoData": "No demo data to clear",
    "demoDataCleared": "Demo data cleared",
    "layoutApplied": "Machine layout applied",
    "default60LayoutRestored": "Default 60-machine layout restored",
    "applyLayoutFirst": "Apply the layout before setting machine properties",
    "emptySlotCannotPause": "An empty slot cannot be paused",
    "emptySlotOnlyRestore": "An empty slot can only be restored; its type or zone cannot be changed",
    "selectMachineType": "Select a machine type",
    "nothingToSaveThisWeek": "There is no patient or staff schedule to save this week",
    "weekSavedAsRecurringTemplate": "This week was saved as the recurring weekly template",
    "noPreviousDaySchedule": "No schedule exists for the previous day",
    "previousDayCopied": "Previous-day schedule copied",
    "noScheduleToday": "No schedule exists for this date",
    "dayScheduleCleared": "Daily schedule cleared",
    "dataImported": "Data imported",
    "importFileUnrecognized": "The import file could not be recognized",
    "allReset": "All data reset",
    "machineNotInLayout": "The machine number is not in the current layout",
    "slotNotInLayout": "The slot is not in the current layout",
    "keepAtLeastOneMachine": "At least one machine must remain",
    "duplicateDialysisNoConfirm": "The dialysis number duplicates {patientName}. Save anyway?",
    "deletePatientConfirm": "Delete {patientName}'s record and related schedules?",
    "duplicateStaffNoConfirm": "The staff number duplicates {staffName}. Save anyway?",
    "deleteStaffConfirm": "Delete {staffName}'s record and related staff schedules?",
    "clearDemoConfirm": "Clear {patientCount} demo patients and {staffCount} demo staff members?",
    "layoutHidesAssignmentsConfirm": "The new layout will hide {count} existing assignments. Apply it anyway?",
    "copyOverwritesCurrentDateConfirm": "The selected date already has a schedule. Copying will overwrite it. Continue?",
    "clearDateScheduleConfirm": "Clear the schedule for {date}?"
  }
};
window.DYNAMIC_MESSAGES = DYNAMIC_MESSAGES;

const STATIC_UI_MESSAGES = {
  "zh-CN": {
    "static_001": "血透室本地排班系统",
    "static_002": "血透室本地排班系统",
    "static_003": "本地自动保存，打开后自动读取",
    "static_004": "日期",
    "static_005": "打印",
    "static_006": "导出",
    "static_007": "导入",
    "static_008": "全部重置",
    "static_009": "清空所有缓存",
    "static_010": "关于作者和程序",
    "static_011": "排班台",
    "static_012": "患者库",
    "static_013": "医护库",
    "static_014": "布局设置",
    "static_015": "上一周",
    "static_016": "本周排班",
    "static_017": "默认读取每周模板，可对单日单独调整",
    "static_018": "下一周",
    "static_019": "今天",
    "static_020": "今日排班",
    "static_021": "排班策略",
    "static_022": "病人优先",
    "static_023": "医护优先",
    "static_024": "灵巧排班",
    "static_025": "生成长期周模板建议",
    "static_026": "本周设为长期模板",
    "static_027": "复制前一天",
    "static_028": "清空当日",
    "static_029": "新增患者",
    "static_030": "新建",
    "static_031": "姓名",
    "static_032": "透析号",
    "static_033": "性别",
    "static_034": "未填",
    "static_035": "男",
    "static_036": "女",
    "static_037": "年龄",
    "static_038": "联系电话",
    "static_039": "干体重 kg",
    "static_040": "血管通路",
    "static_041": "未填",
    "static_042": "自体内瘘",
    "static_043": "人工血管",
    "static_044": "长期导管",
    "static_045": "临时导管",
    "static_046": "其他",
    "static_047": "常规治疗",
    "static_048": "血透",
    "static_049": "血滤",
    "static_050": "灌流",
    "static_051": "每周次数",
    "static_052": "每4周血滤次数",
    "static_053": "仅用于常规血透患者；血滤或灌流患者不再另行生成月度血滤。",
    "static_054": "状态",
    "static_055": "在透",
    "static_056": "暂停",
    "static_057": "感染标识",
    "static_058": "无",
    "static_059": "护理组别",
    "static_060": "普通组",
    "static_061": "严重组",
    "static_062": "常用班次",
    "static_063": "不限",
    "static_064": "上午",
    "static_065": "下午",
    "static_066": "长期固定机位",
    "static_067": "首次自动排班后固定",
    "static_068": "周模板会长期使用该机位；临时换位请保存为仅当前日期。月度血滤在固定机位不支持血滤时可临时换机。",
    "static_069": "透析星期倾向",
    "static_070": "周一",
    "static_071": "周二",
    "static_072": "周三",
    "static_073": "周四",
    "static_074": "周五",
    "static_075": "周六",
    "static_076": "周日",
    "static_077": "备注",
    "static_078": "保存患者",
    "static_079": "删除患者",
    "static_080": "患者列表",
    "static_081": "姓名",
    "static_082": "透析号",
    "static_083": "通路",
    "static_084": "治疗",
    "static_085": "班次",
    "static_086": "状态",
    "static_087": "操作",
    "static_088": "医护排班",
    "static_089": "保存范围",
    "static_090": "每周重复",
    "static_091": "仅当前日期",
    "static_092": "新增医护",
    "static_093": "新建",
    "static_094": "姓名",
    "static_095": "工号",
    "static_096": "角色",
    "static_097": "护士",
    "static_098": "医生",
    "static_099": "联系电话",
    "static_100": "上班倾向",
    "static_101": "不限",
    "static_102": "上午",
    "static_103": "下午",
    "static_104": "状态",
    "static_105": "在岗",
    "static_106": "停用",
    "static_107": "备注",
    "static_108": "保存医护",
    "static_109": "删除医护",
    "static_110": "医护列表",
    "static_111": "姓名",
    "static_112": "工号",
    "static_113": "角色",
    "static_114": "倾向",
    "static_115": "状态",
    "static_116": "操作",
    "static_117": "基础设置",
    "static_118": "语言 / Language",
    "static_119": "中文",
    "static_120": "科室名称",
    "static_121": "每排机器数",
    "static_122": "机器排数",
    "static_123": "第一台从哪边开始",
    "static_124": "左边",
    "static_125": "右边",
    "static_126": "通用传染区名称",
    "static_127": "应用布局",
    "static_128": "恢复默认布局",
    "static_129": "演示数据",
    "static_130": "患者数量",
    "static_131": "医生数量",
    "static_132": "护士数量",
    "static_133": "HBC 患者数量",
    "static_134": "HBV 患者数量",
    "static_135": "HCV 患者数量",
    "static_136": "T 患者数量",
    "static_137": "严重组患者数量",
    "static_138": "演示每4周血滤次数",
    "static_139": "生成演示数据",
    "static_140": "清除演示数据",
    "static_141": "布局预览",
    "static_142": "点击设置",
    "static_143": "设为血透",
    "static_144": "设为血滤",
    "static_145": "设为灌流",
    "static_146": "设为普通区",
    "static_147": "设为重病区",
    "static_148": "设为通用传染区",
    "static_149": "设为 HBC 区",
    "static_150": "设为 HBV 区",
    "static_151": "设为 HCV 区",
    "static_152": "设为 T 区",
    "static_153": "暂停/恢复机器（故障）",
    "static_154": "删除/恢复机位",
    "static_155": "关于作者和程序",
    "static_156": "开源 · 免费 · 祝福所有医护",
    "static_157": "作者本人是透析患者，程序完全开源，完全免费。",
    "static_158": "感谢世界上所有的医护，希望你们每天都开开心心，健健康康。",
    "static_159": "有任何需求、建议或问题，欢迎联系：",
    "static_160": "卓韵",
    "static_161": "关闭",
    "static_162": "安排患者",
    "static_163": "患者",
    "static_164": "备注",
    "static_165": "保存范围",
    "static_166": "每周重复",
    "static_167": "仅当前日期",
    "static_168": "移除",
    "static_169": "取消",
    "static_170": "保存",
    "static_171": "删除本程序保存的数据并强制重新载入最新版页面",
    "static_172": "主功能",
    "static_173": "周排班导航",
    "static_174": "机器排班表",
    "static_175": "搜索患者",
    "static_176": "医护排班表",
    "static_177": "搜索姓名、工号、电话",
    "static_178": "如 传染区",
    "static_179": "演示数据",
    "static_180": "关闭"
  },
  "zh-TW": {
    "static_001": "血透室本地排班系統",
    "static_002": "血透室本地排班系統",
    "static_003": "本地自動儲存，開啟後自動讀取",
    "static_004": "日期",
    "static_005": "列印",
    "static_006": "匯出",
    "static_007": "匯入",
    "static_008": "全部重設",
    "static_009": "清除所有快取",
    "static_010": "關於作者與程式",
    "static_011": "排班台",
    "static_012": "病患庫",
    "static_013": "醫護庫",
    "static_014": "配置設定",
    "static_015": "上一週",
    "static_016": "本週排班",
    "static_017": "默认读取每周模板，可对单日单独调整",
    "static_018": "下一週",
    "static_019": "今天",
    "static_020": "今日排班",
    "static_021": "排班策略",
    "static_022": "病患優先",
    "static_023": "醫護優先",
    "static_024": "靈巧排班",
    "static_025": "產生長期週範本建議",
    "static_026": "將本週設為長期範本",
    "static_027": "複製前一天",
    "static_028": "清除當日",
    "static_029": "新增病患",
    "static_030": "新建",
    "static_031": "姓名",
    "static_032": "透析號",
    "static_033": "性別",
    "static_034": "未填",
    "static_035": "男",
    "static_036": "女",
    "static_037": "年齡",
    "static_038": "聯絡電話",
    "static_039": "乾體重 kg",
    "static_040": "血管通路",
    "static_041": "未填",
    "static_042": "自體內瘻",
    "static_043": "人工血管",
    "static_044": "長期導管",
    "static_045": "臨時導管",
    "static_046": "其他",
    "static_047": "常規治療",
    "static_048": "血透",
    "static_049": "血濾",
    "static_050": "灌流",
    "static_051": "每週次數",
    "static_052": "每月血濾次數",
    "static_053": "仅用于常规血透患者；血滤或灌流患者不再另行生成月度血滤。",
    "static_054": "狀態",
    "static_055": "在透",
    "static_056": "暫停",
    "static_057": "感染標識",
    "static_058": "無",
    "static_059": "護理組別",
    "static_060": "普通組",
    "static_061": "嚴重組",
    "static_062": "常用班次",
    "static_063": "不限",
    "static_064": "上午",
    "static_065": "下午",
    "static_066": "長期固定機位",
    "static_067": "首次自動排班後固定",
    "static_068": "周模板会长期使用该机位；临时换位请保存为仅当前日期。月度血滤在固定机位不支持血滤时可临时换机。",
    "static_069": "透析星期傾向",
    "static_070": "週一",
    "static_071": "週二",
    "static_072": "週三",
    "static_073": "週四",
    "static_074": "週五",
    "static_075": "週六",
    "static_076": "週日",
    "static_077": "備註",
    "static_078": "儲存病患",
    "static_079": "刪除病患",
    "static_080": "病患列表",
    "static_081": "姓名",
    "static_082": "透析號",
    "static_083": "通路",
    "static_084": "治療",
    "static_085": "班次",
    "static_086": "狀態",
    "static_087": "操作",
    "static_088": "醫護排班",
    "static_089": "儲存範圍",
    "static_090": "每週重複",
    "static_091": "僅目前日期",
    "static_092": "新增醫護",
    "static_093": "新建",
    "static_094": "姓名",
    "static_095": "工號",
    "static_096": "角色",
    "static_097": "護士",
    "static_098": "醫生",
    "static_099": "聯絡電話",
    "static_100": "上班傾向",
    "static_101": "不限",
    "static_102": "上午",
    "static_103": "下午",
    "static_104": "狀態",
    "static_105": "在崗",
    "static_106": "停用",
    "static_107": "備註",
    "static_108": "儲存醫護",
    "static_109": "刪除醫護",
    "static_110": "醫護列表",
    "static_111": "姓名",
    "static_112": "工號",
    "static_113": "角色",
    "static_114": "傾向",
    "static_115": "狀態",
    "static_116": "操作",
    "static_117": "基礎設定",
    "static_118": "语言 / Language",
    "static_119": "中文",
    "static_120": "科室名稱",
    "static_121": "每排機器數",
    "static_122": "機器排數",
    "static_123": "第一台從哪邊開始",
    "static_124": "左邊",
    "static_125": "右邊",
    "static_126": "通用傳染區名稱",
    "static_127": "套用配置",
    "static_128": "恢復預設配置",
    "static_129": "示範資料",
    "static_130": "病患數量",
    "static_131": "醫生數量",
    "static_132": "護士數量",
    "static_133": "HBC 患者数量",
    "static_134": "HBV 患者数量",
    "static_135": "HCV 患者数量",
    "static_136": "T 患者数量",
    "static_137": "嚴重組病患數量",
    "static_138": "演示每4周血滤次数",
    "static_139": "產生示範資料",
    "static_140": "清除示範資料",
    "static_141": "配置預覽",
    "static_142": "點擊設定",
    "static_143": "設為血透",
    "static_144": "設為血濾",
    "static_145": "設為灌流",
    "static_146": "設為普通區",
    "static_147": "設為重病區",
    "static_148": "設為通用傳染區",
    "static_149": "设为 HBC 区",
    "static_150": "设为 HBV 区",
    "static_151": "设为 HCV 区",
    "static_152": "设为 T 区",
    "static_153": "暫停/恢復機器（故障）",
    "static_154": "刪除/恢復機位",
    "static_155": "關於作者與程式",
    "static_156": "開源 · 免費 · 祝福所有醫護",
    "static_157": "作者本人是透析患者，程序完全开源，完全免费。",
    "static_158": "感谢世界上所有的医护，希望你们每天都开开心心，健健康康。",
    "static_159": "有任何需求、建议或问题，欢迎联系：",
    "static_160": "卓韵",
    "static_161": "關閉",
    "static_162": "安排病患",
    "static_163": "病患",
    "static_164": "備註",
    "static_165": "儲存範圍",
    "static_166": "每週重複",
    "static_167": "僅目前日期",
    "static_168": "移除",
    "static_169": "取消",
    "static_170": "儲存",
    "static_171": "删除本程序保存的数据并强制重新载入最新版页面",
    "static_172": "主要功能",
    "static_173": "週排班導覽",
    "static_174": "機器排班表",
    "static_175": "搜尋病患",
    "static_176": "醫護排班表",
    "static_177": "搜尋姓名、工號、電話",
    "static_178": "如 传染区",
    "static_179": "示範資料",
    "static_180": "關閉"
  },
  "en": {
    "static_001": "Hemodialysis Room Local Scheduler",
    "static_002": "Hemodialysis Room Local Scheduler",
    "static_003": "Automatically saved locally and loaded when opened",
    "static_004": "Date",
    "static_005": "Print",
    "static_006": "Export",
    "static_007": "Import",
    "static_008": "Reset All",
    "static_009": "Clear All Cache",
    "static_010": "About the Author and Program",
    "static_011": "Schedule",
    "static_012": "Patients",
    "static_013": "Staff",
    "static_014": "Layout Settings",
    "static_015": "Previous Week",
    "static_016": "This Week",
    "static_017": "Weekly templates are loaded by default; individual dates can be adjusted separately",
    "static_018": "Next Week",
    "static_019": "Today",
    "static_020": "Today’s Schedule",
    "static_021": "Scheduling Strategy",
    "static_022": "Patient Priority",
    "static_023": "Staff Priority",
    "static_024": "Smart Scheduling",
    "static_025": "Generate Recurring Weekly Template",
    "static_026": "Set This Week as Recurring Template",
    "static_027": "Copy Previous Day",
    "static_028": "Clear Current Day",
    "static_029": "Add Patient",
    "static_030": "New",
    "static_031": "Name",
    "static_032": "Dialysis ID",
    "static_033": "Sex",
    "static_034": "Not Specified",
    "static_035": "Male",
    "static_036": "Female",
    "static_037": "Age",
    "static_038": "Phone",
    "static_039": "Dry Weight (kg)",
    "static_040": "Vascular Access",
    "static_041": "Not Specified",
    "static_042": "AV Fistula",
    "static_043": "AV Graft",
    "static_044": "Tunneled Catheter",
    "static_045": "Temporary Catheter",
    "static_046": "Other",
    "static_047": "Routine Treatment",
    "static_048": "Hemodialysis",
    "static_049": "Hemofiltration",
    "static_050": "Hemoperfusion",
    "static_051": "Treatments per Week",
    "static_052": "Monthly Hemofiltration Sessions",
    "static_053": "Only for routine hemodialysis patients; monthly hemofiltration is not generated separately for hemofiltration or hemoperfusion patients.",
    "static_054": "Status",
    "static_055": "Active",
    "static_056": "Paused",
    "static_057": "Infection Status",
    "static_058": "None",
    "static_059": "Care Group",
    "static_060": "Standard Group",
    "static_061": "Severe-Care Group",
    "static_062": "Preferred Shift",
    "static_063": "Any",
    "static_064": "Morning",
    "static_065": "Afternoon",
    "static_066": "Long-Term Fixed Machine",
    "static_067": "Fix after First Automatic Schedule",
    "static_068": "The recurring weekly template will keep this machine. Save temporary moves for the selected date only. Monthly hemofiltration may temporarily use another machine if the fixed machine is incompatible.",
    "static_069": "Preferred Treatment Days",
    "static_070": "Monday",
    "static_071": "Tuesday",
    "static_072": "Wednesday",
    "static_073": "Thursday",
    "static_074": "Friday",
    "static_075": "Saturday",
    "static_076": "Sunday",
    "static_077": "Notes",
    "static_078": "Save Patient",
    "static_079": "Delete Patient",
    "static_080": "Patient List",
    "static_081": "Name",
    "static_082": "Dialysis ID",
    "static_083": "Access",
    "static_084": "Treatment",
    "static_085": "Shift",
    "static_086": "Status",
    "static_087": "Actions",
    "static_088": "Staff Schedule",
    "static_089": "Save Scope",
    "static_090": "Recurring Weekly",
    "static_091": "Selected Date Only",
    "static_092": "Add Staff",
    "static_093": "New",
    "static_094": "Name",
    "static_095": "Staff ID",
    "static_096": "Role",
    "static_097": "Nurse",
    "static_098": "Doctor",
    "static_099": "Phone",
    "static_100": "Work Preference",
    "static_101": "Any",
    "static_102": "Morning",
    "static_103": "Afternoon",
    "static_104": "Status",
    "static_105": "Active",
    "static_106": "Inactive",
    "static_107": "Notes",
    "static_108": "Save Staff",
    "static_109": "Delete Staff",
    "static_110": "Staff List",
    "static_111": "Name",
    "static_112": "Staff ID",
    "static_113": "Role",
    "static_114": "Preference",
    "static_115": "Status",
    "static_116": "Actions",
    "static_117": "Basic Settings",
    "static_118": "Language",
    "static_119": "Chinese",
    "static_120": "Department Name",
    "static_121": "Machines per Row",
    "static_122": "Number of Rows",
    "static_123": "First Machine Starts From",
    "static_124": "Left",
    "static_125": "Right",
    "static_126": "Shared Infection Zone Name",
    "static_127": "Apply Layout",
    "static_128": "Restore Default Layout",
    "static_129": "Demo Data",
    "static_130": "Patient Count",
    "static_131": "Doctor Count",
    "static_132": "Nurse Count",
    "static_133": "HBC Patient Count",
    "static_134": "HBV Patient Count",
    "static_135": "HCV Patient Count",
    "static_136": "T Patient Count",
    "static_137": "Severe-Care Patient Count",
    "static_138": "Demo 4-week Hemofiltration Sessions",
    "static_139": "Generate Demo Data",
    "static_140": "Clear Demo Data",
    "static_141": "Layout Preview",
    "static_142": "Click to Configure",
    "static_143": "Set as Hemodialysis",
    "static_144": "Set as Hemofiltration",
    "static_145": "Set as Hemoperfusion",
    "static_146": "Set as Standard Zone",
    "static_147": "Set as Severe-Care Zone",
    "static_148": "Set as Shared Infection Zone",
    "static_149": "Set as HBC Zone",
    "static_150": "Set as HBV Zone",
    "static_151": "Set as HCV Zone",
    "static_152": "Set as T Zone",
    "static_153": "Pause/Restore Machine (Failure)",
    "static_154": "Delete/Restore Slot",
    "static_155": "About the Author and Program",
    "static_156": "Open Source · Free · Best Wishes to All Healthcare Workers",
    "static_157": "The author is a dialysis patient. This program is fully open source and completely free.",
    "static_158": "Thank you to all healthcare workers around the world. May you be happy and healthy every day.",
    "static_159": "For requests, suggestions, or questions, please contact:",
    "static_160": "Zhuo Yun",
    "static_161": "Close",
    "static_162": "Assign Patient",
    "static_163": "Patient",
    "static_164": "Notes",
    "static_165": "Save Scope",
    "static_166": "Recurring Weekly",
    "static_167": "Selected Date Only",
    "static_168": "Remove",
    "static_169": "Cancel",
    "static_170": "Save",
    "static_171": "Delete this application’s saved data and force reload the latest version",
    "static_172": "Main Functions",
    "static_173": "Weekly Schedule Navigation",
    "static_174": "Machine Schedule",
    "static_175": "Search Patients",
    "static_176": "Staff Schedule",
    "static_177": "Search name, staff ID, or phone",
    "static_178": "e.g. Infection Zone",
    "static_179": "Demo Data",
    "static_180": "Close"
  }
};
window.STATIC_UI_MESSAGES = STATIC_UI_MESSAGES;

const RUNTIME_TEXT_MESSAGES = {
  "zh-CN": {
    "上午": "上午",
    "下午": "下午",
    "普通区": "普通区",
    "重病区": "重病区",
    "通用传染区": "通用传染区",
    "血透": "血透",
    "血滤": "血滤",
    "灌流": "灌流",
    "灵巧排班": "灵巧排班",
    "医护优先": "医护优先",
    "患者优先": "患者优先",
    "周一": "周一",
    "周二": "周二",
    "周三": "周三",
    "周四": "周四",
    "周五": "周五",
    "周六": "周六",
    "周日": "周日",
    "完成率": "完成率",
    "当前班次无需安排医护": "当前班次无需安排医护",
    "医护岗位": "医护岗位",
    "传染分类": "传染分类",
    "患者分类": "患者分类",
    "重复排班": "重复排班",
    "同一患者在同一班次被重复安排，请尽快检查": "同一患者在同一班次被重复安排，请尽快检查",
    "需处理": "需处理",
    "单班": "单班",
    "每日": "每日",
    "每周": "每周",
    "折算患者": "折算患者",
    "治疗能力总览": "治疗能力总览",
    "理论容量": "理论容量",
    "多余旧岗位": "多余旧岗位",
    "待清理": "待清理",
    "后备护士": "后备护士",
    "无患者，但存在旧医护记录": "无患者，但存在旧医护记录",
    "请清空本班旧医护记录，或先安排患者。": "请清空本班旧医护记录，或先安排患者。",
    "未安排": "未安排",
    "先到医护库新增": "先到医护库新增",
    "不限": "不限",
    "严重组": "严重组",
    "暂无患者": "暂无患者",
    "本班次暂无护士管区": "本班次暂无护士管区",
    "空位": "空位",
    "暂停": "暂停",
    "单日调整": "单日调整",
    "周模板": "周模板",
    "机器暂停": "机器暂停",
    "机器已暂停，请调整患者": "机器已暂停，请调整患者",
    "普通血透患者可设置未来 4 周内的血滤次数": "普通血透患者可设置未来 4 周内的血滤次数",
    "常规治疗不是血透时，不再另行生成月度血滤": "常规治疗不是血透时，不再另行生成月度血滤",
    "新增患者": "新增患者",
    "暂无患者资料": "暂无患者资料",
    "在透": "在透",
    "待首次排班固定": "待首次排班固定",
    "基本资料待完善": "基本资料待完善",
    "新增医护": "新增医护",
    "暂无医护资料": "暂无医护资料",
    "停用": "停用",
    "在岗": "在岗",
    "医生": "医生",
    "护士": "护士",
    "资料待完善": "资料待完善",
    "编辑": "编辑",
    "排班": "排班",
    "恢复默认 60 台机器布局吗？": "恢复默认 60 台机器布局吗？",
    "首次自动排班后固定": "首次自动排班后固定",
    "已暂停": "已暂停",
    "本周已有的单日调整会转入长期模板，并从这些日期的临时调整中移除。": "本周已有的单日调整会转入长期模板，并从这些日期的临时调整中移除。",
    "周日仍作为休息日；周日临时加班不会写入长期模板。": "周日仍作为休息日；周日临时加班不会写入长期模板。",
    "灵巧排班（全部每周3次患者采用安全弹性组合，优化护士班组）": "灵巧排班（全部每周3次患者采用安全弹性组合，优化护士班组）",
    "医护优先（集中患者，尽量减少开班班次）": "医护优先（集中患者，尽量减少开班班次）",
    "患者优先（尽量保持患者原星期和班次倾向）": "患者优先（尽量保持患者原星期和班次倾向）",
    "范围：周一至周六排班，周日休息。": "范围：周一至周六排班，周日休息。",
    "需要人工复核：": "需要人工复核：",
    "与“患者优先”排班方案相比：": "与“患者优先”排班方案相比：",
    "患者优先基准方案未通过完整安全校验，本次仅显示灵巧排班自身结果：": "患者优先基准方案未通过完整安全校验，本次仅显示灵巧排班自身结果：",
    "所有结果仍需医护人员人工复核后执行。": "所有结果仍需医护人员人工复核后执行。",
    "当前没有可生成周模板的在透患者。请先在患者库设置透析星期倾向。": "当前没有可生成周模板的在透患者。请先在患者库设置透析星期倾向。",
    "护士人数不足以完全避免跨班重复，系统已优先按倾向和均衡原则安排。": "护士人数不足以完全避免跨班重复，系统已优先按倾向和均衡原则安排。",
    "确定全部重置吗？这会清空本地保存的患者资料、患者排班、医护排班、机器类型和特殊区机器设置。": "确定全部重置吗？这会清空本地保存的患者资料、患者排班、医护排班、机器类型和特殊区机器设置。",
    "已全部重置，本地数据已清空": "已全部重置，本地数据已清空"
  },
  "zh-TW": {
    "上午": "上午",
    "下午": "下午",
    "普通区": "普通区",
    "重病区": "重病区",
    "通用传染区": "通用传染区",
    "血透": "血透",
    "血滤": "血滤",
    "灌流": "灌流",
    "灵巧排班": "灵巧排班",
    "医护优先": "医护优先",
    "患者优先": "患者优先",
    "周一": "周一",
    "周二": "周二",
    "周三": "周三",
    "周四": "周四",
    "周五": "周五",
    "周六": "周六",
    "周日": "周日",
    "完成率": "完成率",
    "当前班次无需安排医护": "当前班次无需安排医护",
    "医护岗位": "医护岗位",
    "传染分类": "传染分类",
    "患者分类": "患者分类",
    "重复排班": "重复排班",
    "同一患者在同一班次被重复安排，请尽快检查": "同一患者在同一班次被重复安排，请尽快检查",
    "需处理": "需处理",
    "单班": "单班",
    "每日": "每日",
    "每周": "每周",
    "折算患者": "折算患者",
    "治疗能力总览": "治疗能力总览",
    "理论容量": "理论容量",
    "多余旧岗位": "多余旧岗位",
    "待清理": "待清理",
    "后备护士": "后备护士",
    "无患者，但存在旧医护记录": "无患者，但存在旧医护记录",
    "请清空本班旧医护记录，或先安排患者。": "请清空本班旧医护记录，或先安排患者。",
    "未安排": "未安排",
    "先到医护库新增": "先到医护库新增",
    "不限": "不限",
    "严重组": "严重组",
    "暂无患者": "暂无患者",
    "本班次暂无护士管区": "本班次暂无护士管区",
    "空位": "空位",
    "暂停": "暂停",
    "单日调整": "单日调整",
    "周模板": "周模板",
    "机器暂停": "机器暂停",
    "机器已暂停，请调整患者": "机器已暂停，请调整患者",
    "普通血透患者可设置未来 4 周内的血滤次数": "普通血透患者可设置未来 4 周内的血滤次数",
    "常规治疗不是血透时，不再另行生成月度血滤": "常规治疗不是血透时，不再另行生成月度血滤",
    "新增患者": "新增患者",
    "暂无患者资料": "暂无患者资料",
    "在透": "在透",
    "待首次排班固定": "待首次排班固定",
    "基本资料待完善": "基本资料待完善",
    "新增医护": "新增医护",
    "暂无医护资料": "暂无医护资料",
    "停用": "停用",
    "在岗": "在岗",
    "医生": "医生",
    "护士": "护士",
    "资料待完善": "资料待完善",
    "编辑": "编辑",
    "排班": "排班",
    "恢复默认 60 台机器布局吗？": "恢复默认 60 台机器布局吗？",
    "首次自动排班后固定": "首次自动排班后固定",
    "已暂停": "已暂停",
    "本周已有的单日调整会转入长期模板，并从这些日期的临时调整中移除。": "本周已有的单日调整会转入长期模板，并从这些日期的临时调整中移除。",
    "周日仍作为休息日；周日临时加班不会写入长期模板。": "周日仍作为休息日；周日临时加班不会写入长期模板。",
    "灵巧排班（全部每周3次患者采用安全弹性组合，优化护士班组）": "灵巧排班（全部每周3次患者采用安全弹性组合，优化护士班组）",
    "医护优先（集中患者，尽量减少开班班次）": "医护优先（集中患者，尽量减少开班班次）",
    "患者优先（尽量保持患者原星期和班次倾向）": "患者优先（尽量保持患者原星期和班次倾向）",
    "范围：周一至周六排班，周日休息。": "范围：周一至周六排班，周日休息。",
    "需要人工复核：": "需要人工复核：",
    "与“患者优先”排班方案相比：": "与“患者优先”排班方案相比：",
    "患者优先基准方案未通过完整安全校验，本次仅显示灵巧排班自身结果：": "患者优先基准方案未通过完整安全校验，本次仅显示灵巧排班自身结果：",
    "所有结果仍需医护人员人工复核后执行。": "所有结果仍需医护人员人工复核后执行。",
    "当前没有可生成周模板的在透患者。请先在患者库设置透析星期倾向。": "当前没有可生成周模板的在透患者。请先在患者库设置透析星期倾向。",
    "护士人数不足以完全避免跨班重复，系统已优先按倾向和均衡原则安排。": "护士人数不足以完全避免跨班重复，系统已优先按倾向和均衡原则安排。",
    "确定全部重置吗？这会清空本地保存的患者资料、患者排班、医护排班、机器类型和特殊区机器设置。": "确定全部重置吗？这会清空本地保存的患者资料、患者排班、医护排班、机器类型和特殊区机器设置。",
    "已全部重置，本地数据已清空": "已全部重置，本地数据已清空"
  },
  "en": {
    "上午": "Morning",
    "下午": "Afternoon",
    "普通区": "Standard Zone",
    "重病区": "Severe-Care Zone",
    "通用传染区": "Shared Infection Zone",
    "血透": "Hemodialysis",
    "血滤": "Hemofiltration",
    "灌流": "Hemoperfusion",
    "灵巧排班": "Smart Scheduling",
    "医护优先": "Staff Priority",
    "患者优先": "Patient Priority",
    "周一": "Monday",
    "周二": "Tuesday",
    "周三": "Wednesday",
    "周四": "Thursday",
    "周五": "Friday",
    "周六": "Saturday",
    "周日": "Sunday",
    "完成率": "Completion Rate",
    "当前班次无需安排医护": "No staff assignment is required for the current shift",
    "医护岗位": "Staff Positions",
    "传染分类": "Infection Categories",
    "患者分类": "Patient Categories",
    "重复排班": "Duplicate Assignment",
    "同一患者在同一班次被重复安排，请尽快检查": "The same patient is assigned more than once in the same shift. Review immediately.",
    "需处理": "Action Required",
    "单班": "Per Shift",
    "每日": "Per Day",
    "每周": "Per Week",
    "折算患者": "Estimated Patients",
    "治疗能力总览": "Treatment Capacity Overview",
    "理论容量": "Theoretical Capacity",
    "多余旧岗位": "Obsolete Position",
    "待清理": "Cleanup Required",
    "后备护士": "Backup Nurse",
    "无患者，但存在旧医护记录": "No patients are assigned, but obsolete staff records remain",
    "请清空本班旧医护记录，或先安排患者。": "Clear obsolete staff records for this shift or assign patients first.",
    "未安排": "Unassigned",
    "先到医护库新增": "Add staff in the Staff Library first",
    "不限": "Any",
    "严重组": "Severe-Care Group",
    "暂无患者": "No Patients",
    "本班次暂无护士管区": "No nurse responsibility zone for this shift",
    "空位": "Empty Slot",
    "暂停": "Paused",
    "单日调整": "Date-Specific Adjustment",
    "周模板": "Weekly Template",
    "机器暂停": "Machine Paused",
    "机器已暂停，请调整患者": "Machine is paused. Reassign the patient.",
    "普通血透患者可设置未来 4 周内的血滤次数": "Routine hemodialysis patients may set hemofiltration sessions for the next 4 weeks",
    "常规治疗不是血透时，不再另行生成月度血滤": "Monthly hemofiltration is not generated when the routine treatment is not hemodialysis",
    "新增患者": "Add Patient",
    "暂无患者资料": "No Patient Records",
    "在透": "Active",
    "待首次排班固定": "Fix after First Schedule",
    "基本资料待完善": "Basic information incomplete",
    "新增医护": "Add Staff",
    "暂无医护资料": "No Staff Records",
    "停用": "Inactive",
    "在岗": "Active",
    "医生": "Doctor",
    "护士": "Nurse",
    "资料待完善": "Information incomplete",
    "编辑": "Edit",
    "排班": "Schedule",
    "恢复默认 60 台机器布局吗？": "Restore the default 60-machine layout?",
    "首次自动排班后固定": "Fix after First Automatic Schedule",
    "已暂停": "Paused",
    "本周已有的单日调整会转入长期模板，并从这些日期的临时调整中移除。": "Existing date-specific adjustments for this week will be converted into the recurring template and removed from temporary overrides.",
    "周日仍作为休息日；周日临时加班不会写入长期模板。": "Sunday remains a rest day; temporary Sunday work will not be added to the recurring template.",
    "灵巧排班（全部每周3次患者采用安全弹性组合，优化护士班组）": "Smart Scheduling (all thrice-weekly patients use safe flexible patterns to optimize nurse groups)",
    "医护优先（集中患者，尽量减少开班班次）": "Staff Priority (concentrate patients and reduce active shifts where possible)",
    "患者优先（尽量保持患者原星期和班次倾向）": "Patient Priority (preserve preferred treatment days and shifts where possible)",
    "范围：周一至周六排班，周日休息。": "Scope: Monday through Saturday scheduling; Sunday is a rest day.",
    "需要人工复核：": "Manual Review Required:",
    "与“患者优先”排班方案相比：": "Compared with the Patient Priority schedule:",
    "患者优先基准方案未通过完整安全校验，本次仅显示灵巧排班自身结果：": "The Patient Priority baseline did not pass the complete safety audit. Only the current Smart Scheduling results are shown.",
    "所有结果仍需医护人员人工复核后执行。": "All results must be manually reviewed by healthcare staff before use.",
    "当前没有可生成周模板的在透患者。请先在患者库设置透析星期倾向。": "There are no active patients available for weekly-template generation. Set preferred treatment days in the patient library first.",
    "护士人数不足以完全避免跨班重复，系统已优先按倾向和均衡原则安排。": "There are not enough nurses to completely avoid cross-shift duplication. The system prioritized preferences and workload balance.",
    "确定全部重置吗？这会清空本地保存的患者资料、患者排班、医护排班、机器类型和特殊区机器设置。": "Reset everything? This will erase locally saved patient records, patient schedules, staff schedules, machine types, and special-zone settings.",
    "已全部重置，本地数据已清空": "All data has been reset and local storage has been cleared"
  }
};
const RUNTIME_TEXT_PATTERNS = [
  {
    "pattern": "^第\\s*(\\d+)\\s*排$",
    "replacements": {
      "en": "Row $1"
    }
  },
  {
    "pattern": "^(\\d+)\\s*个岗位$",
    "replacements": {
      "en": "$1 positions"
    }
  },
  {
    "pattern": "^医生\\s*(\\d+)$",
    "replacements": {
      "en": "Doctor $1"
    }
  },
  {
    "pattern": "^责任护士\\s*(\\d+)$",
    "replacements": {
      "en": "Primary Nurse $1"
    }
  },
  {
    "pattern": "^(\\d+)/(\\d+)人$",
    "replacements": {
      "en": "$1/$2 patients"
    }
  },
  {
    "pattern": "^血滤(\\d+)台$",
    "replacements": {
      "en": "$1 hemofiltration machine(s)"
    }
  },
  {
    "pattern": "^固定\\s*(\\d+)号机$",
    "replacements": {
      "en": "Fixed machine $1"
    }
  },
  {
    "pattern": "^(\\d+)次/周\\s*·\\s*血滤(\\d+)次/月$",
    "replacements": {
      "en": "$1/week · Hemofiltration $2/month"
    }
  },
  {
    "pattern": "^(\\d+)岁$",
    "replacements": {
      "en": "Age $1"
    }
  },
  {
    "pattern": "^(\\d+)号机$",
    "replacements": {
      "en": "Machine $1"
    }
  },
  {
    "pattern": "^(\\d+)\\s*人$",
    "replacements": {
      "en": "$1 patients"
    }
  },
  {
    "pattern": "^本周需求\\s*(\\d+)\\s*·\\s*剩余\\s*(\\d+)\\s*·\\s*今日\\s*(\\d+)%$",
    "replacements": {
      "en": "Weekly demand $1 · Remaining $2 · Today $3%"
    }
  },
  {
    "pattern": "^实际开班：(\\d+)\\s*个班次，关闭\\s*(\\d+)\\s*个空班次$",
    "replacements": {
      "en": "Active shifts: $1; closed empty shifts: $2"
    }
  },
  {
    "pattern": "^调整透析日期：(\\d+)\\s*名患者，共\\s*(\\d+)\\s*次治疗$",
    "replacements": {
      "en": "Treatment dates adjusted: $1 patients, $2 sessions"
    }
  },
  {
    "pattern": "^调整上午/下午班次：(\\d+)\\s*次$",
    "replacements": {
      "en": "Morning/afternoon shift adjustments: $1"
    }
  },
  {
    "pattern": "^减少开班班次：(-?\\d+)\\s*个（当前\\s*(\\d+)\\s*个）$",
    "replacements": {
      "en": "Active shifts reduced by $1 (current: $2)"
    }
  },
  {
    "pattern": "^减少责任护士岗位：(-?\\d+)\\s*个（当前\\s*(\\d+)\\s*个）$",
    "replacements": {
      "en": "Primary-nurse positions reduced by $1 (current: $2)"
    }
  },
  {
    "pattern": "^减少单人护士组：(-?\\d+)\\s*个（当前\\s*(\\d+)\\s*个）$",
    "replacements": {
      "en": "Single-patient nurse groups reduced by $1 (current: $2)"
    }
  },
  {
    "pattern": "^减少低负荷护士组（1—2人）：(-?\\d+)\\s*个（当前\\s*(\\d+)\\s*个）$",
    "replacements": {
      "en": "Low-load nurse groups (1–2 patients) reduced by $1 (current: $2)"
    }
  }
];
window.RUNTIME_TEXT_MESSAGES = RUNTIME_TEXT_MESSAGES;
window.RUNTIME_TEXT_PATTERNS = RUNTIME_TEXT_PATTERNS;
